apiVersion: v1
kind: ConfigMap
metadata:
  name: shipping
  namespace: roboshop
  labels:
    project: roboshop
    tier: backend
    component: shipping
data:
  CART_ENDPOINT: "cart:8080"
  DB_HOST: "mysql"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  namespace: roboshop
  # these labels are replicaset labels
  labels:
    project: roboshop
    tier: backend
    component: shipping
spec:
  replicas: 1
  selector:
    # using these labels replica set selects the pod
    matchLabels:
      project: roboshop
      tier: backend
      component: shipping
  # This is pod definition, pod is subset of replicaset
  template:
    metadata:
      labels:
        project: roboshop
        tier: backend
        component: shipping
    spec:
      containers:
      - name: shipping
        image: joindevops/shipping:1.4.0
        imagePullPolicy: Always # safe to pull everytime, there may be images with same version rebuilt and pushed
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        readinessProbe:
          # httpGet:
          #   path: /health
          #   port: 8080
          tcpSocket:
            port: 8080
          failureThreshold: 2
          periodSeconds: 10
          initialDelaySeconds: 15
        startupProbe:
          httpGet:
            path: /health
            port: 8080
          failureThreshold: 20
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          failureThreshold: 2
          periodSeconds: 10
        envFrom:
        - configMapRef:
            name: shipping
---
apiVersion: v1
kind: Service
metadata:
  name: shipping
  namespace: roboshop
  labels:
    project: roboshop
    tier: backend
    component: shipping
spec:
  selector:
    # labels are used as selectors
    project: roboshop
    tier: backend
    component: shipping
  ports:
  - protocol: TCP
    port: 8080 # servie port
    targetPort: 8080 # container port