apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq
  namespace: roboshop
  labels:
    project: roboshop
    tier: db
    component: rabbitmq
data:
  RABBITMQ_DEFAULT_USER: roboshop
  RABBITMQ_DEFAULT_PASS: roboshop123
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: roboshop
  # these labels are replicaset labels
  labels:
    project: roboshop
    tier: db
    component: rabbitmq
spec:
  replicas: 1
  selector:
    # using these labels replica set selects the pod
    matchLabels:
      project: roboshop
      tier: db
      component: rabbitmq
  # This is pod definition, pod is subset of replicaset
  template:
    metadata:
      labels:
        project: roboshop
        tier: db
        component: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3
        envFrom:
        - configMapRef:
            name: rabbitmq
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: roboshop
  labels:
    project: roboshop
    tier: db
    component: rabbitmq
spec:
  selector:
    # labels are used as selectors
    project: roboshop
    tier: db
    component: rabbitmq
  ports:
  - protocol: TCP
    port: 5672 # servie port
    targetPort: 5672 # container port