apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    project: roboshop
    tier: backend
    component: catalogue
data:
  MONGO: "true"
  MONGO_URL: "mongodb://mongodb:27017/catalogue"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  namespace: roboshop
  # these labels are replicaset labels
  labels:
    project: roboshop
    tier: backend
    component: catalogue
spec:
  replicas: 1
  selector:
    # using these labels replica set selects the pod
    matchLabels:
      project: roboshop
      tier: backend
      component: catalogue
  # This is pod definition, pod is subset of replicaset
  template:
    metadata:
      labels:
        project: roboshop
        tier: backend
        component: catalogue
    spec:
      containers:
      - name: catalogue
        image: joindevops/catalogue:1.4.0
        imagePullPolicy: Always # safe to pull everytime, there may be images with same version rebuilt and pushed
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"
        readinessProbe:
          # httpGet:
          #   path: /health
          #   port: 8080
          tcpSocket:
            port: 8080
          failureThreshold: 2
          periodSeconds: 10
          initialDelaySeconds: 15
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          failureThreshold: 2
          periodSeconds: 10
        envFrom:
        - configMapRef:
            name: catalogue
---
apiVersion: v1
kind: Service
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    project: roboshop
    tier: backend
    component: catalogue
spec:
  selector:
    # labels are used as selectors
    project: roboshop
    tier: backend
    component: catalogue
  ports:
  - protocol: TCP
    port: 8080 # servie port
    targetPort: 8080 # container port